CREATE TABLE "services" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"category_id" text NOT NULL,
	"duration_minutes" integer NOT NULL,
	"price_cents" integer NOT NULL,
	"deposit_cents" integer,
	"cancellation_cents" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "services_category_id_idx" ON "services" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "services_active_sort_idx" ON "services" USING btree ("is_active","sort_order");
--> statement-breakpoint
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('customized-facial', 'Customized Facial', 'A facial tailored to your skin''s unique needs. Deep cleansing, exfoliation, and nourishing hydration restore balance and a radiant glow.', 'skin-care', 45, 7500, 2000, 1500, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('express-facial', 'Express Facial', 'Quick refresh — cleansing, exfoliation, and hydration for instantly revived skin.', 'skin-care', 35, 5000, 1500, 1500, 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('facial-foot-bath', 'Facial w/ Foot Bath', 'A full customized facial paired with a soothing foot bath for total head-to-toe relaxation.', 'skin-care', 60, 7500, 2000, 1500, 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('back-facial', 'Back Facial', 'A purifying treatment targeting congestion, dryness, and uneven texture on the back.', 'skin-care', 60, 6500, 2000, 1500, 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('back-scrub', 'Back Scrub', 'Deep exfoliation that smooths texture and refreshes the skin on the back.', 'skin-care', 45, 5000, 1500, 1500, 40) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('bum-scrub', 'Bum Scrub', 'Gentle exfoliating treatment designed to smooth and refine the skin.', 'skin-care', 30, 2500, 1000, 1000, 50) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('full-body-scrub', 'Full Body Scrub', 'Head-to-toe exfoliation that polishes, brightens, and softens the entire body.', 'skin-care', 75, 15000, 3000, 2000, 60) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('foot-detox', 'Foot Detox', 'Cleansing foot soak designed to draw out impurities and leave you grounded.', 'skin-care', 45, 3500, 1500, 1500, 70) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('vajacial', 'Vajacial', 'Post-wax treatment designed to prevent ingrown hairs, calm irritation, and restore smooth skin.', 'skin-care', 30, 5000, 1500, 1500, 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('brazilian-wax', 'Brazilian Wax', 'Full Brazilian wax for a smooth, clean finish.', 'waxing', 25, 6500, 2000, 1500, 90) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('manzilian', 'Manzilian', 'Full male Brazilian wax for complete smoothness and comfort.', 'waxing', 30, 8500, 2000, 1500, 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('bikini-wax', 'Bikini Wax', 'Clean-up wax along the bikini line.', 'waxing', 15, 3500, 1500, 1500, 110) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('bum-wax', 'Bum (Butt) Wax', 'Targeted wax for the bum area.', 'waxing', 15, 3000, 1500, 1500, 120) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('full-leg-wax', 'Full Leg Wax', 'Complete leg wax from ankle to upper thigh.', 'waxing', 45, 8000, 2000, 1500, 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('half-leg-wax', 'Half Leg Wax', 'Lower or upper leg wax for smooth, hair-free skin.', 'waxing', 30, 4000, 1500, 1500, 140) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('half-arm-wax', 'Half Arm Wax', 'Wax from wrist to elbow or elbow to shoulder.', 'waxing', 30, 3500, 1500, 1500, 150) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('underarm-wax', 'Underarm Wax', 'Quick underarm wax for clean, smooth results.', 'waxing', 15, 2500, 1000, 1000, 160) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('inner-thigh-wax', 'Inner Thigh Wax', 'Targeted wax for the inner thigh area.', 'waxing', 15, 2000, 1000, 1000, 170) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('belly-wax', 'Belly (Happy Trail) Wax', 'Quick wax for the happy trail / lower belly area.', 'waxing', 5, 1500, 1000, 1000, 180) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('back-wax', 'Back Wax', 'Full back hair removal for a clean, smooth finish.', 'waxing', 30, 6000, 2000, 1500, 190) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('men-chest-wax', 'Men Chest Wax', 'Full chest wax for a smooth, defined look.', 'waxing', 30, 5000, 1500, 1500, 200) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('men-abdomen-wax', 'Men Abdomen (Stomach) Wax', 'Stomach area wax for a clean finish.', 'waxing', 30, 2500, 1000, 1000, 210) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('facial-wax', 'Facial Wax', 'Full-face hair removal — brows, lip, chin, and any peach fuzz.', 'waxing', 25, 5000, 1500, 1500, 220) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('eyebrow-wax', 'Eyebrow Wax', 'Clean, defined brow shaping with professional wax.', 'waxing', 10, 2000, 1000, 1000, 230) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('eyebrow-tint-wax', 'Eyebrow Tint w/ Wax', 'Full brow service combining semi-permanent tint and wax shaping.', 'waxing', 25, 3500, 1500, 1500, 240) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('beard-wax', 'Beard Wax', 'Beard line clean-up and shaping.', 'waxing', 30, 3000, 1500, 1500, 250) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('neck-wax', 'Neck Wax', 'Clean up the neckline for a polished look.', 'waxing', 10, 1500, 1000, 1000, 260) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('chin-wax', 'Chin Wax', 'Quick chin area hair removal.', 'waxing', 5, 1500, 1000, 1000, 270) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('upper-lip-wax', 'Upper Lip Wax', 'Quick, clean upper lip hair removal.', 'waxing', 10, 1000, 1000, 1000, 280) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('stress-relief-massage', 'Stress Relief Massage', 'A relaxing massage designed to ease tension and restore balance.', 'self-care', 60, 8500, 2000, 1500, 290) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('yoni-steam', 'Yoni Steam (V-Steaming)', 'A calming herbal steam ritual supporting feminine wellness and deep relaxation.', 'self-care', 60, 6500, 2000, 1500, 300) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('express-yoni-steam', 'Express Yoni Steam (V-Steaming)', 'A streamlined herbal steam session for a quick reset.', 'self-care', 30, 4000, 1500, 1500, 310) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('foot-bath-scrub', 'Foot Bath w/ Scrub', 'Soothing foot soak paired with a polishing scrub.', 'self-care', 30, 2500, 1000, 1000, 320) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('express-back-facial', 'Express Back Facial', 'A streamlined back facial designed to cleanse and refresh quickly.', 'self-care', 35, 5000, 1500, 1500, 330) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('individual-lashes', 'Individual Lashes', 'Natural-looking lash enhancement applied lash-by-lash.', 'self-care', 45, 3000, 1500, 1500, 340) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('lash-bath', 'Lash Bath', 'Gentle cleansing treatment to refresh and maintain your lash extensions.', 'self-care', 5, 1000, 1000, 1000, 350) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('lash-removal', 'Lash Removal', 'Safe professional removal of lash extensions.', 'self-care', 30, 2500, 1000, 1000, 360) ON CONFLICT (id) DO NOTHING;
INSERT INTO "services" (id, name, description, category_id, duration_minutes, price_cents, deposit_cents, cancellation_cents, sort_order) VALUES ('eyebrow-tint', 'Eyebrow Tint (Only)', 'Semi-permanent color to fill and define your brows.', 'self-care', 20, 2500, 1000, 1000, 370) ON CONFLICT (id) DO NOTHING;
