// ── Service Categories ──

export const serviceCategories = [
  {
    id: 'skin-care',
    name: 'Skin Care',
    services: [
      {
        id: 'customized-facial',
        name: 'Customized Facial',
        description: 'A facial tailored to your skin\'s unique needs. Deep cleansing, exfoliation, and nourishing hydration restore balance and a radiant glow.',
        duration: '45 min',
        price: '$75',
        priceNum: 75,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'express-facial',
        name: 'Express Facial',
        description: 'Quick refresh — cleansing, exfoliation, and hydration for instantly revived skin.',
        duration: '35 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'facial-foot-bath',
        name: 'Facial w/ Foot Bath',
        description: 'A full customized facial paired with a soothing foot bath for total head-to-toe relaxation.',
        duration: '1 hr',
        price: '$75',
        priceNum: 75,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'back-facial',
        name: 'Back Facial',
        description: 'A purifying treatment targeting congestion, dryness, and uneven texture on the back.',
        duration: '1 hr',
        price: '$65',
        priceNum: 65,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'back-scrub',
        name: 'Back Scrub',
        description: 'Deep exfoliation that smooths texture and refreshes the skin on the back.',
        duration: '45 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'bum-scrub',
        name: 'Bum Scrub',
        description: 'Gentle exfoliating treatment designed to smooth and refine the skin.',
        duration: '30 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'full-body-scrub',
        name: 'Full Body Scrub',
        description: 'Head-to-toe exfoliation that polishes, brightens, and softens the entire body.',
        duration: '1 hr 15 min',
        price: '$150',
        priceNum: 150,
        deposit: '$30',
        cancellationFee: '$20',
      },
      {
        id: 'foot-detox',
        name: 'Foot Detox',
        description: 'Cleansing foot soak designed to draw out impurities and leave you grounded.',
        duration: '45 min',
        price: '$35',
        priceNum: 35,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'vajacial',
        name: 'Vajacial',
        description: 'Post-wax treatment designed to prevent ingrown hairs, calm irritation, and restore smooth skin.',
        duration: '30 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
    ],
  },
  {
    id: 'waxing',
    name: 'Waxing',
    services: [
      {
        id: 'brazilian-wax',
        name: 'Brazilian Wax',
        description: 'Full Brazilian wax for a smooth, clean finish.',
        duration: '25 min',
        price: '$100',
        priceNum: 100,
        deposit: '$30',
        cancellationFee: '$20',
      },
      {
        id: 'manzilian',
        name: 'Manzilian',
        description: 'Full male Brazilian wax for complete smoothness and comfort.',
        duration: '30 min',
        price: '$150',
        priceNum: 150,
        deposit: '$30',
        cancellationFee: '$20',
      },
      {
        id: 'bikini-wax',
        name: 'Bikini Wax',
        description: 'Clean-up wax along the bikini line.',
        duration: '15 min',
        price: '$35',
        priceNum: 35,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'bum-wax',
        name: 'Bum (Butt) Wax',
        description: 'Targeted wax for the bum area.',
        duration: '15 min',
        price: '$30',
        priceNum: 30,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'full-leg-wax',
        name: 'Full Leg Wax',
        description: 'Complete leg wax from ankle to upper thigh.',
        duration: '45 min',
        price: '$80',
        priceNum: 80,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'half-leg-wax',
        name: 'Half Leg Wax',
        description: 'Lower or upper leg wax for smooth, hair-free skin.',
        duration: '30 min',
        price: '$40',
        priceNum: 40,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'half-arm-wax',
        name: 'Half Arm Wax',
        description: 'Wax from wrist to elbow or elbow to shoulder.',
        duration: '30 min',
        price: '$35',
        priceNum: 35,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'underarm-wax',
        name: 'Underarm Wax',
        description: 'Quick underarm wax for clean, smooth results.',
        duration: '15 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'inner-thigh-wax',
        name: 'Inner Thigh Wax',
        description: 'Targeted wax for the inner thigh area.',
        duration: '15 min',
        price: '$20',
        priceNum: 20,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'belly-wax',
        name: 'Belly (Happy Trail) Wax',
        description: 'Quick wax for the happy trail / lower belly area.',
        duration: '5 min',
        price: '$15',
        priceNum: 15,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'back-wax',
        name: 'Back Wax',
        description: 'Full back hair removal for a clean, smooth finish.',
        duration: '30 min',
        price: '$60',
        priceNum: 60,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'men-chest-wax',
        name: 'Men Chest Wax',
        description: 'Full chest wax for a smooth, defined look.',
        duration: '30 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'men-abdomen-wax',
        name: 'Men Abdomen (Stomach) Wax',
        description: 'Stomach area wax for a clean finish.',
        duration: '30 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'facial-wax',
        name: 'Facial Wax',
        description: 'Full-face hair removal — brows, lip, chin, and any peach fuzz.',
        duration: '25 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'eyebrow-wax',
        name: 'Eyebrow Wax',
        description: 'Clean, defined brow shaping with professional wax.',
        duration: '10 min',
        price: '$20',
        priceNum: 20,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'eyebrow-tint-wax',
        name: 'Eyebrow Tint w/ Wax',
        description: 'Full brow service combining semi-permanent tint and wax shaping.',
        duration: '25 min',
        price: '$35',
        priceNum: 35,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'beard-wax',
        name: 'Beard Wax',
        description: 'Beard line clean-up and shaping.',
        duration: '30 min',
        price: '$30',
        priceNum: 30,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'neck-wax',
        name: 'Neck Wax',
        description: 'Clean up the neckline for a polished look.',
        duration: '10 min',
        price: '$15',
        priceNum: 15,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'chin-wax',
        name: 'Chin Wax',
        description: 'Quick chin area hair removal.',
        duration: '5 min',
        price: '$15',
        priceNum: 15,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'upper-lip-wax',
        name: 'Upper Lip Wax',
        description: 'Quick, clean upper lip hair removal.',
        duration: '10 min',
        price: '$10',
        priceNum: 10,
        deposit: '$10',
        cancellationFee: '$10',
      },
    ],
  },
  {
    id: 'self-care',
    name: 'Self Care',
    services: [
      {
        id: 'stress-relief-massage',
        name: 'Stress Relief Massage',
        description: 'A relaxing massage designed to ease tension and restore balance.',
        duration: '1 hr',
        price: '$85',
        priceNum: 85,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'yoni-steam',
        name: 'Yoni Steam (V-Steaming)',
        description: 'A calming herbal steam ritual supporting feminine wellness and deep relaxation.',
        duration: '1 hr',
        price: '$65',
        priceNum: 65,
        deposit: '$20',
        cancellationFee: '$15',
      },
      {
        id: 'express-yoni-steam',
        name: 'Express Yoni Steam (V-Steaming)',
        description: 'A streamlined herbal steam session for a quick reset.',
        duration: '30 min',
        price: '$40',
        priceNum: 40,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'foot-bath-scrub',
        name: 'Foot Bath w/ Scrub',
        description: 'Soothing foot soak paired with a polishing scrub.',
        duration: '30 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'express-back-facial',
        name: 'Express Back Facial',
        description: 'A streamlined back facial designed to cleanse and refresh quickly.',
        duration: '35 min',
        price: '$50',
        priceNum: 50,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'individual-lashes',
        name: 'Individual Lashes',
        description: 'Natural-looking lash enhancement applied lash-by-lash.',
        duration: '45 min',
        price: '$30',
        priceNum: 30,
        deposit: '$15',
        cancellationFee: '$15',
      },
      {
        id: 'lash-bath',
        name: 'Lash Bath',
        description: 'Gentle cleansing treatment to refresh and maintain your lash extensions.',
        duration: '5 min',
        price: '$10',
        priceNum: 10,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'lash-removal',
        name: 'Lash Removal',
        description: 'Safe professional removal of lash extensions.',
        duration: '30 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
      {
        id: 'eyebrow-tint',
        name: 'Eyebrow Tint (Only)',
        description: 'Semi-permanent color to fill and define your brows.',
        duration: '20 min',
        price: '$25',
        priceNum: 25,
        deposit: '$10',
        cancellationFee: '$10',
      },
    ],
  },
];

// Flat list of all services (for lookup)
export const services = serviceCategories.flatMap((cat) => cat.services);

// ── Add-Ons ──

export const addOns = [
  {
    id: 'extractions',
    name: 'Extractions',
    duration: '20 min',
    price: '$20',
    priceNum: 20,
  },
  {
    id: 'hydrojelly-mask',
    name: 'HydroJelly Mask',
    duration: '20 min',
    price: '$15',
    priceNum: 15,
  },
  {
    id: 'plant-peel',
    name: 'Plant Peel',
    duration: '20 min',
    price: '$20',
    priceNum: 20,
  },
  {
    id: 'turmeric-clay-mask',
    name: 'Turmeric Clay Mask',
    duration: '20 min',
    price: '$15',
    priceNum: 15,
  },
];

// ── Policies ──

export const bookingPolicies = [
  { id: 'deposit', label: 'Deposit', value: 'Required to secure slot' },
  { id: 'late-cancel', label: 'Late cancel', value: '50% of service inside 24 hours' },
  { id: 'no-show', label: 'No-show', value: '100% of deposit forfeited' },
  { id: 'reschedule', label: 'Reschedule', value: 'Free outside 24 hours' },
];

export const cancellationPolicy = [
  {
    title: '24-hour flexibility',
    body: 'Guests can cancel or reschedule outside the 24-hour window with no penalty.',
  },
  {
    title: 'Late cancellation fee',
    body: 'Inside 24 hours, a defined late cancellation fee will be charged through Stripe.',
  },
  {
    title: 'No-show protection',
    body: 'Deposits or pre-authorized payment methods prevent revenue loss from missed appointments.',
  },
];

// ── Dashboard (sample data for admin) ──

export const dashboardStats = {
  weeklyRevenue: '$3,860',
  bookedThisWeek: '28 bookings',
  retentionPipeline: '12 guests due for follow-up',
  cards: [
    { label: 'This week', value: '$3,860', detail: 'Deposits, completed services, and fees.' },
    { label: 'Occupancy', value: '82%', detail: 'Fill rate across your calendar.' },
    { label: 'Repeat clients', value: '61%', detail: 'Returning for follow-up treatments.' },
    { label: 'Fees recovered', value: '$245', detail: 'From late cancellations and no-shows.' },
  ],
};

export const weeklyRevenue = [
  { day: 'Monday', total: '$540', note: 'Good morning fill driven by member discounts.' },
  { day: 'Tuesday', total: '$675', note: 'Package upgrades converted well after reminders.' },
  { day: 'Wednesday', total: '$490', note: 'Open capacity midday for quick brow and lash services.' },
  { day: 'Thursday', total: '$935', note: 'Prime day for premium facials and pre-weekend prep.' },
  { day: 'Friday', total: '$1,220', note: 'Highest demand with strong repeat customer mix.' },
];

export const customerRoster = [
  {
    id: 'cust-1',
    name: 'Ashley Lacy',
    email: 'ashley@example.com',
    segment: 'VIP',
    story: 'Books monthly customized facials and usually adds a HydroJelly mask.',
    lifetimeSpend: '$1,480',
    lastVisit: 'February 28',
    nextAction: 'Send loyalty bonus after next completed appointment.',
  },
  {
    id: 'cust-2',
    name: 'Jaz Monroe',
    email: 'jaz@example.com',
    segment: 'Win-back',
    story: 'Regular Brazilian client who has rescheduled twice due to work conflicts.',
    lifetimeSpend: '$520',
    lastVisit: 'January 14',
    nextAction: 'Offer weekday recovery slot and reminder sequence.',
  },
  {
    id: 'cust-3',
    name: 'Leah Warren',
    email: 'leah@example.com',
    segment: 'New',
    story: 'First-time express facial client, candidate for a full customized facial upsell.',
    lifetimeSpend: '$50',
    lastVisit: 'March 12',
    nextAction: 'Send aftercare guide and 4-week rebook nudge.',
  },
];

export const retentionAutomations = [
  {
    title: '24-hour reminder',
    copy: 'Email with arrival details, prep notes, and a quick link to change or cancel.',
    trigger: '24 hours before appointment',
  },
  {
    title: 'Post-treatment aftercare',
    copy: 'Product suggestions, booking recap, and next-step guidance.',
    trigger: '2 hours after appointment',
  },
  {
    title: 'Four-week rebook prompt',
    copy: 'Invite facial clients to reserve their next session.',
    trigger: '28 days after service',
  },
];
